version: '3'
services:
  aws:
    build: .
    stdin_open: true
    tty: true
    # 必要に応じて適宜プロジェクトをマウント
    volumes:
      - .ssh:/root/.ssh
      - .aws:/root/.aws
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c 'service docker start; /bin/bash'
    
